# Change these first
owner: TheRealToxicDev # Your GitHub username
repo: InfinityBotsStatus # Your GitHub repository name

# Add your sites here
sites:
  - name: API
    url: https://api.infinitybots.xyz
  - name: Main Site
    url: https://infinitybots.xyz

status-website:
  theme: night
  # cname: demo.upptime.js.org
  baseUrl: /InfinityBotsStatus
  logoUrl: https://media.discordapp.net/attachments/734686866690932767/817198822035554314/image0.png
  name: Infinity Bots
  introTitle: "**Infinity Bot List Status**."
  introMessage: Real Time status updates for all of our Available Services.
  navbar:
    - title: Discord
      href: https://infinitybots.xyz/discord
    - title: Twitter
      href: https://twitter.com/InfinityBotList
    - title: GitHub
      href: https://github.com/InfinityBotList
