# Change these first
owner: TheRealToxicDev # Your GitHub username
repo: InfinityBotsStatus # Your GitHub repository name

# Add your sites here
sites:
  - name: API
    url: https://api.infinitybotlist.com
  - name: CDN Storage
    url: https://cdn.infinitybots.xyz
  - name: Cloudflare
    url: https://cloudflare.com
  - name: Docs Site
    url: https://docs.infinitybotlist.com
  - name: Guide Site
    url: https://guide.infinitybotlist.com
  - name: Main Site
    url: https://infinitybotlist.com
  - name: Short Domains
    url: https://ibl.rocks
  - name: Ticket Transcripts
    url: https://tickets.infinitybots.xyz
  - name: Transcript API
    url: https://api.tickets.infinitybots.xyz/api/v1/get/13996274
  - name: Staff Panel
    url: https://infinitybotlist.com/panel
  - name: Queue Panel
    url: https://infinitybotlist.com/panel/queue
  - name: Certification Panel
    url: https://infinitybotlist.com/panel/certification



status-website:
  favicon: https://cdn.infinitybots.xyz/images/png/InfinityOld.png
  theme: night
  cname: status.infinitybotlist.com
  # baseUrl: /InfinityBotsStatus
  logoUrl: https://cdn.infinitybots.xyz/images/png/InfinityOld.png
  name: Infinity Bots
  introTitle: "**Infinity Bot List Status**."
  introMessage: Real Time status updates for all of our Available Services.
  navbar:
    - title: Discord
      href: https://discord.gg/MCydkq2F
    - title: Twitter
      href: https://twitter.com/InfinityBotList

commitMessages:
  commitAuthorName: "Infinity Status Bot"
  commitAuthorEmail: "support@infinitybots.xyz"

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

i18n:
  footer: Made with ❤️ By Toxic Dev | All Rights Reserved
  url: "URL"
  status: "Status"
  history: "History"
  responseTime: "Response Time"
  uptime: "Uptime"
  responseTimeGraphAlt: "Response time graph"
  allSystemsOperational: "All systems operational"
  degradedPerformance: "Degraded performance"
  completeOutage: "Major Outage"
  partialOutage: "Minor outage"
