# Change these first
owner: TheRealToxicDev # Your GitHub username
repo: InfinityBotsStatus # Your GitHub repository name

# Add your sites here
sites:
  - name: API
    url: https://api.infinitybots.xyz
  - name: CDN Storage
    url: https://cdn.infinitybots.xyz
  - name: Cloudflare
    url: https://cloudflare.com
  - name: Docs Site
    url: https://docs.infinitybots.xyz
  - name: Guide Site
    url: https://guide.infinitybots.xyz
  - name: Main Site
    url: https://infinitybots.xyz
  - name: Short Domains
    url: https://botlist.site
  - name: Ticket Transcripts
    url: https://tickets.infinitybots.xyz
  - name: Transcript API
    url: https://api.tickets.infinitybots.xyz



status-website:
  favicon: https://cdn.infinitybots.xyz/images/png/InfinityOld.png
  theme: night
  # cname: demo.upptime.js.org
  baseUrl: /InfinityBotsStatus
  logoUrl: https://cdn.infinitybots.xyz/images/gif/InfinityBots.gif
  name: Infinity Bots
  introTitle: "**Infinity Bot List Status**."
  introMessage: Real Time status updates for all of our Available Services.
  navbar:
    - title: Discord
      href: https://infinitybots.xyz/discord
    - title: Twitter
      href: https://twitter.com/InfinityBotList

i18n:
  footer: Made with 仇벒잺 By Toxic Dev | All Rights Reserved
  url: "URL"
  status: "Status"
  history: "History"
  responseTime: "Response Time"
  uptime: "Uptime"
  up: "游릴 Up"
  degraded: "游릳 Degraded"
  down: "游린 Down"
  responseTimeGraphAlt: "Response time graph"
  ms: "ms"
  responseTime: "Response time"
  responseTimeDay: "24-hour response time"
  responseTimeWeek: "7-day response time"
  responseTimeMonth: "30-day response time"
  responseTimeYear: "1-year response time"
  uptime: "All-time uptime"
  uptimeDay: "24-hour uptime"
  uptimeWeek: "7-day uptime"
  uptimeMonth: "30-day uptime"
  uptimeYear: "1-year uptime"
  liveStatus: "Live Status"
  allSystemsOperational: "游릴 All systems operational"
  degradedPerformance: "游릳 Degraded performance"
  completeOutage: "游린 Complete outage"
  partialOutage: "游릲 Partial outage"
